"""Phase 7: make the site legible to something that is not a browser.

The problem this solves is not that the site lacks a sitemap. It is that the
site has almost no HTML. Every deal, score, verdict and club dashboard is
written into an empty `<div>` by JavaScript at runtime, so a crawler that does
not execute scripts sees four headings and some empty containers. Google will
usually render JavaScript eventually; Bing is patchier, and the social and
chat crawlers that build link previews do not run it at all. A sitemap
pointing at an empty page just tells more crawlers where the empty page is.

So the order of work here is deliberate:

1. Pre-render the real content into the existing containers. The site's own
   JavaScript overwrites them on load, so the browser experience is
   unchanged and the crawler experience goes from nothing to everything.
2. Give the content URLs. One page with four tabs is one indexable document,
   and "Arsenal transfer spend" has nowhere to land. Club and deal pages turn
   one thin URL into dozens of specific ones.
3. Only then, the plumbing: sitemap, robots, feed, structured data.

Everything is generated from `data.json` at build time, so it cannot drift
from what the pipeline believes.
"""

from __future__ import annotations

import html
import json
import re
from dataclasses import dataclass
from datetime import date, datetime, timezone
from html.parser import HTMLParser
from typing import Iterable

from .entities import fold_for_slug
from .models import Deal, Evidence

# The generated head block is delimited at both ends so a rerun can remove
# exactly what the previous run added, leaving the author's own whitespace and
# hand-written tags untouched.
GEN_START = "<!-- generated by scripts/render_site.py, do not hand edit -->"
GEN_END = "<!-- /generated -->"

STATUS_LABEL = {
    "rumor": "Rumour",
    "talks": "In talks",
    "agreed": "Fee agreed",
    "medical": "Medical booked",
    "confirmed": "Confirmed pending announcement",
    "done": "Completed",
    "collapsed": "Collapsed",
}

#: Short form for places where the full label will not fit, e.g. a table cell
#: or the funnel chips.
STATUS_SHORT = dict(STATUS_LABEL, confirmed="Confirmed")

STATUS_ORDER = ["rumor", "talks", "agreed", "medical", "confirmed", "done",
                "collapsed"]

#: TI-002. The one definition of which deals the value section assesses.
#: The scatter chart and the verdicts table both read this, which is the
#: whole point: they used to filter separately, and a table that disagreed
#: with the chart above it was indistinguishable from a table that was broken.
VALUE_STATUSES = frozenset({"agreed", "medical", "confirmed", "done"})


def value_eligible(deals: Iterable[Deal]) -> list[Deal]:
    """Deals with a confirmed fee worth assessing, best first.

    Free transfers are excluded deliberately rather than incidentally. A value
    score divides a fee by a rating, and a fee of zero makes every free signing
    an infinitely good deal, which is true in a sense that helps nobody.
    """
    rows = [
        d for d in deals
        if (d.fee or 0) > 0
        and str(getattr(d.status, "value", d.status)) in VALUE_STATUSES
    ]
    return sorted(rows, key=lambda d: (-(d.fee or 0), d.p))


# ---------------------------------------------------------------- config


@dataclass
class SiteConfig:
    """Everything the renderer needs that is not in the deal data.

    `base_url` is the one value that has to be right. Canonical tags, Open
    Graph URLs and the sitemap all require absolute URLs, and a wrong origin
    is worse than none: it tells crawlers the real page is somewhere else.
    """

    base_url: str = ""
    title: str = "TransferIntel"
    description: str = (
        "Premier League transfer rumours scored 0 to 100 for credibility, "
        "with transparent value-for-money verdicts on confirmed fees."
    )
    author: str = "Peter Brendan"
    twitter: str = ""
    locale: str = "en_GB"

    #: TI-010. The provider's hosted form endpoint. Empty means no capture
    #: form is rendered at all, which is the right default: a form that posts
    #: nowhere collects addresses into a void and burns the one chance you get
    #: to ask a visitor for their email.
    newsletter_action: str = ""
    newsletter_provider: str = ""

    #: TI-012. Cloudflare Web Analytics token. Empty means no snippet.
    analytics_token: str = ""
    goatcounter: str = ""

    @classmethod
    def from_data(cls, raw: dict) -> "SiteConfig":
        config = raw.get("config") or {}
        site = config.get("site") or {}
        news = config.get("newsletter") or {}
        stats = config.get("analytics") or {}
        return cls(
            base_url=str(site.get("baseUrl", "")).rstrip("/"),
            title=site.get("title", cls.title),
            description=site.get("description", cls.description),
            author=site.get("author", cls.author),
            twitter=site.get("twitter", ""),
            locale=site.get("locale", cls.locale),
            newsletter_action=str(news.get("action", "")),
            newsletter_provider=str(news.get("provider", "")),
            analytics_token=str(stats.get("cloudflareToken", "")),
            goatcounter=str(stats.get("goatcounter", "")),
        )

    @property
    def path_prefix(self) -> str:
        """The sub-path a project site is served from, e.g. /transferintel."""
        if not self.base_url:
            return ""
        after_scheme = self.base_url.split("://", 1)[-1]
        slash = after_scheme.find("/")
        return "" if slash == -1 else after_scheme[slash:].rstrip("/")

    def url(self, path: str) -> str:
        return f"{self.base_url}/{path.lstrip('/')}" if self.base_url else f"/{path.lstrip('/')}"

    def href(self, path: str) -> str:
        """Root-relative link, correct whether or not the site sits in a sub-path."""
        return f"{self.path_prefix}/{path.lstrip('/')}" if path != "/" else f"{self.path_prefix}/"


def slugify(value: str) -> str:
    """URL-safe slug.

    Uses the same transliteration table as entity resolution rather than a
    second copy. NFKD does not decompose characters like O-slash, so a naive
    normalise silently drops them: Odegaard would slug as "degaard", losing
    the first letter of the name and risking a collision with a different
    player. One table, used everywhere, or this bug comes back.
    """
    norm = fold_for_slug(value)
    norm = re.sub(r"[^a-z0-9]+", "-", norm).strip("-")
    return norm or "item"


def e(value) -> str:
    return html.escape(str(value if value is not None else ""), quote=True)


# ------------------------------------------------------- HTML injection


class _Locator(HTMLParser):
    """Find an element by id and report where its content begins and ends.

    A regex over HTML is how you corrupt a file the first time someone adds an
    attribute or a nested tag. This walks the document properly and counts
    depth, so injecting into `<div id="feed">` still works after the div grows
    children or the attribute order changes.
    """

    def __init__(self, target_id: str) -> None:
        super().__init__(convert_charrefs=False)
        self.target = target_id
        self.tag: str | None = None
        self.depth = 0
        self.start: tuple[int, int] | None = None
        self.end: tuple[int, int] | None = None

    def handle_starttag(self, tag, attrs):
        attrs_d = dict(attrs)
        if self.tag is None and attrs_d.get("id") == self.target:
            self.tag = tag
            self.depth = 1
            line, col = self.getpos()
            self.start = (line, col + len(self.get_starttag_text() or ""))
        elif self.tag is not None and tag == self.tag:
            self.depth += 1

    def handle_startendtag(self, tag, attrs):
        if dict(attrs).get("id") == self.target and self.tag is None:
            self.tag = tag
            self.start = None  # self-closing, nothing to fill

    def handle_endtag(self, tag):
        if self.tag is not None and tag == self.tag and self.end is None:
            self.depth -= 1
            if self.depth == 0:
                self.end = self.getpos()


def _offset(text: str, line: int, col: int) -> int:
    lines = text.splitlines(keepends=True)
    return sum(len(l) for l in lines[: line - 1]) + col


def inject_into(document: str, element_id: str, content: str) -> str:
    """Replace the inner HTML of `element_id`. Returns the document unchanged
    if the element is not found, because a missing container is a template the
    author has edited, not a reason to fail a daily build."""
    loc = _Locator(element_id)
    try:
        loc.feed(document)
        loc.close()
    except Exception:
        return document
    if not loc.start or not loc.end:
        return document
    start = _offset(document, *loc.start)
    end = _offset(document, *loc.end)
    if start > end:
        return document
    return document[:start] + content + document[end:]


def inject_head(document: str, content: str) -> str:
    idx = document.lower().rfind("</head>")
    if idx == -1:
        return document
    return document[:idx] + content + document[idx:]


# ------------------------------------------------------------- fragments


def deal_slug(deal: Deal) -> str:
    return slugify(deal.id)


def deal_path(deal: Deal) -> str:
    return f"deals/{deal_slug(deal)}/"


def club_path(club: str) -> str:
    return f"clubs/{slugify(club)}/"


def cred_class(cred: int) -> str:
    if cred >= 75:
        return "high"
    if cred >= 50:
        return "mid"
    if cred >= 25:
        return "low"
    return "vlow"


def deal_sentence(deal: Deal) -> str:
    """One plain sentence per deal, the thing a crawler and a screen reader
    both actually read."""
    fee = f" for a reported £{deal.fee:g}m" if deal.fee else ""
    status = STATUS_LABEL.get(
        deal.status.value if hasattr(deal.status, "value") else str(deal.status),
        str(deal.status),
    )
    return (
        f"{deal.p}, {deal.pos or 'player'}"
        f"{f', age {deal.age}' if deal.age else ''}, "
        f"from {deal.from_club} to {deal.to}{fee}. "
        f"Status: {status}. Credibility {deal.cred} out of 100, "
        f"based on {deal.src or 'reported sources'}."
    )


# ------------------------------------------------------------- value model


def value_score(deal: Deal, proven_clubs: Iterable[str] = ()) -> int:
    """The site's transparent value rating, 5 to 98.

    This is a deliberate second implementation of the model in index.html.
    Duplication is normally a smell; here it is the test. The browser copy is
    what a reader sees and the Python copy is what the build can assert
    against, and `test_site.py` checks that both produce the same numbers for
    every deal in the dataset. If someone edits one and not the other, the
    build says so.
    """
    score = 50.0
    peak = 25
    if deal.age <= 24:
        score += (24 - deal.age) * 2.2
    else:
        score -= abs(deal.age - peak) * 3.2
    if deal.pos in {"AM", "ST", "LW", "RW"}:
        score += 6
    if deal.pos == "CM":
        score += 4
    if deal.from_club in set(proven_clubs):
        score += 8
    if deal.age >= 30:
        score -= 8
    return max(5, min(98, round(score)))


#: Fee per value point, and what that ratio is called. Ordered ascending.
VERDICT_BANDS: tuple[tuple[float, str, str], ...] = (
    (0.55, "Bargain", "v-bargain"),
    (0.95, "Fair", "v-fair"),
    (1.35, "Premium", "v-premium"),
    (float("inf"), "Overpay risk", "v-overpay"),
)


def verdict(deal: Deal, proven_clubs: Iterable[str] = ()) -> tuple[str, str]:
    if not deal.fee:
        return "Bargain", "v-bargain"
    ratio = deal.fee / value_score(deal, proven_clubs)
    for limit, label, css in VERDICT_BANDS:
        if ratio < limit:
            return label, css
    return "Overpay risk", "v-overpay"


#: TI-002. Never render bare headers. A table with a header row and no body
#: is indistinguishable from a broken page, and it was one.
VALUE_EMPTY_ROW = (
    '<tr class="empty"><td colspan="6">No confirmed fees yet this window. '
    "Free transfers are excluded from value scoring.</td></tr>"
)


def render_value_rows(deals: list[Deal], proven_clubs: Iterable[str] = ()) -> str:
    """The verdicts table body, pre-rendered from the same collection the
    scatter chart uses."""
    rows = value_eligible(deals)
    if not rows:
        return VALUE_EMPTY_ROW
    out = []
    for d in rows:
        label, css = verdict(d, proven_clubs)
        out.append(
            f'<tr class="clickable" data-id="{e(d.id)}">'
            f"<td><b>{e(d.p)}</b></td>"
            f'<td class="move">{e(d.from_club)} to {e(d.to)}</td>'
            f"<td>{d.age}</td>"
            f"<td>£{d.fee:g}m</td>"
            f"<td>{value_score(d, proven_clubs)}</td>"
            f'<td><span class="verdict {css}">{e(label)}</span></td></tr>'
        )
    return "\n".join(out)


# ---------------------------------------------------------- email capture

#: TI-010. The promise, not the ask. "Subscribe to updates" describes what the
#: reader does for you; this describes what they get, how often, and when it
#: stops, which is the part that makes an unsubscribe unnecessary later.
CAPTURE_COPY = (
    "Every morning: what actually moved, and what was noise. "
    "One email a day while the window is open, and it stops when it closes."
)


def render_capture_form(
    cfg: SiteConfig, clubs: Iterable[str], placement: str,
    with_preferences: bool = False,
) -> str:
    """The signup form, posting straight to the provider's hosted endpoint.

    No backend, because there is no backend. The form is real HTML that works
    without JavaScript, and the redirect target is a page the analytics
    provider can count as a conversion (TI-012).
    """
    if not cfg.newsletter_action:
        return ""

    prefs = ""
    if with_preferences:
        # TI-011. Two fields, both optional, both defaulted to "everything",
        # and both folded away behind a disclosure. A signup form that demands
        # decisions before it will take an address is a signup form people
        # close, and this is now the only form on the page: it has to ask for
        # one thing, and let the rest be optional detail for the minority who
        # want it.
        options = "".join(
            f'<option value="{e(c)}">{e(c)}</option>' for c in sorted(clubs)
        )
        prefs = f"""
  <details class="capture-more">
    <summary>Only want certain clubs?</summary>
      <div class="capture-prefs">
        <label>Clubs
          <select name="fields[clubs]" multiple size="4"
                  aria-label="Clubs to follow, leave unset for all">
            <option value="all" selected>All clubs</option>
            {options}
          </select>
        </label>
        <label>Minimum credibility
          <select name="fields[threshold]">
            <option value="0" selected>Anything tracked</option>
            <option value="40">40 and above</option>
            <option value="60">60 and above</option>
            <option value="80">80 and above</option>
            <option value="confirmed">Confirmed only</option>
          </select>
        </label>
      </div>
  </details>"""

    return f"""<form class="capture" method="post"
      action="{e(cfg.newsletter_action)}"
      data-placement="{e(placement)}" data-ti-event="newsletter_submit">
  <h3>The daily transfer digest</h3>
  <p>{e(CAPTURE_COPY)}</p>
  <div class="capture-row">
    <label class="visually-hidden" for="email-{e(placement)}">Email address</label>
    <input id="email-{e(placement)}" type="email" name="email_address" required
           autocomplete="email" placeholder="you@example.com">
    <button type="submit">Get the digest</button>
  </div>{prefs}
  <input type="hidden" name="redirect" value="{e(cfg.url('thanks/'))}">
  <p class="capture-small">Double opt-in. One click to unsubscribe. No ads,
  no list sharing.</p>
</form>"""


def render_thanks_page(cfg: SiteConfig, updated_iso: str) -> str:
    """The post-submit landing page, and the analytics conversion goal."""
    body = """
<h1>Check your inbox</h1>
<p class="lede">One more click and you are in. We have sent a confirmation
email; the digest will not start until you open it.</p>
<div class="panel">
<p><strong>What arrives, and when.</strong> One email each morning while the
window is open. New deals tracked, status changes, credibility movements of 15
points or more, and collapses. On a quiet day it says so in two lines rather
than padding.</p>
</div>
<p>Nothing in the inbox after a few minutes? Check spam, and look for the
sender you approved at signup.</p>
"""
    body += f'<p><a href="{e(cfg.href("/"))}">Back to the window index</a></p>'
    return standalone_page(
        cfg, title=f"You are almost subscribed | {cfg.title}",
        description="Confirm your subscription to the TransferIntel daily digest.",
        path="thanks/", og_image="og/default.png", updated_iso=updated_iso,
        breadcrumb=f'<a href="{e(cfg.href("/"))}">TransferIntel</a> / subscribe',
        body=body, ld="",
    )


# -------------------------------------------------------------- analytics


def render_analytics(cfg: SiteConfig) -> str:
    """TI-012. Pageviews plus six named events, under 5KB, no cookies.

    Cloudflare Web Analytics is cookieless and needs no consent banner, which
    is why it is the base layer rather than the more familiar alternative. The
    event helper is deliberately provider-agnostic: it pushes to whichever of
    the two scripts is present and does nothing at all if neither is, so
    removing a provider never leaves a page throwing on every click.
    """
    parts = []
    if cfg.analytics_token:
        parts.append(
            '<script defer src="https://static.cloudflareinsights.com/beacon.min.js" '
            f"data-cf-beacon='{{\"token\": \"{e(cfg.analytics_token)}\"}}'></script>"
        )
    if cfg.goatcounter:
        parts.append(
            f'<script data-goatcounter="{e(cfg.goatcounter)}" '
            'async src="//gc.zgo.at/count.js"></script>'
        )
    parts.append("""<script>
/* TI-012. Six events, one helper, no library. */
(function(){
  function send(name, detail){
    try{
      if(window.goatcounter && window.goatcounter.count){
        window.goatcounter.count({path:name+(detail?":"+detail:""),
                                  title:name, event:true});
      }
      if(window.__cfBeacon){ /* Cloudflare records pageviews only */ }
      window.dispatchEvent(new CustomEvent("ti:event",
        {detail:{name:name, detail:detail}}));
    }catch(err){ /* analytics must never break the page */ }
  }
  window.tiTrack = send;
  document.addEventListener("click", function(ev){
    var form = ev.target.closest && ev.target.closest("form.capture");
    if(form){ send("newsletter_submit", form.dataset.placement); return; }
    var link = ev.target.closest && ev.target.closest("a");
    if(!link) return;
    var href = link.getAttribute("href") || "";
    if(/^https?:\\/\\//.test(href) && link.hostname !== location.hostname){
      send("outbound_source", link.hostname);
    }else if(href.indexOf("/deals/") !== -1){
      send("deal_opened", href.split("/deals/")[1].replace(/\\/$/,""));
    }else if(href.indexOf("/clubs/") !== -1){
      send("club_opened", href.split("/clubs/")[1].replace(/\\/$/,""));
    }
  }, true);
  if(location.pathname.indexOf("/thanks") !== -1){ send("newsletter_confirmed"); }
})();
</script>""")
    return "\n".join(parts)


def best_source_link(deal: Deal) -> Evidence | None:
    """The best piece of evidence a reader can actually open.

    Tier 1 first, then most recent. Migrated records carry `urn:` evidence
    rather than a link, so a large part of the dataset has none and gets no
    link at all. That is the honest outcome: there is nothing to send anyone
    to, and a dead link is worse than no link.
    """
    live = [
        e for e in deal.evidence
        if str(e.url).startswith("http")
    ]
    if not live:
        return None
    live.sort(key=lambda e: (e.tier, -e.date.toordinal()))
    return live[0]


def source_anchor(deal: Deal) -> str:
    best = best_source_link(deal)
    if best is None:
        return ""
    return (
        f' <a class="srclink" href="{e(str(best.url))}" target="_blank" '
        f'rel="noopener nofollow">{e(best.source)} &#8599;</a>'
    )


def pos_badge(deal: Deal) -> str:
    return f'<span class="pos">{e(deal.pos)}</span>' if deal.pos else ""


def render_deal_list(deals: Iterable[Deal], cfg: SiteConfig) -> str:
    """The pre-rendered rumour list. The site's JS replaces this on load."""
    rows = []
    for d in deals:
        status = d.status.value if hasattr(d.status, "value") else str(d.status)
        rows.append(
            f'<article class="rumor" id="deal-{e(d.id)}">'
            f'<div class="cred {cred_class(d.cred)}" aria-label="Credibility {d.cred} of 100">'
            f"<span>{d.cred}</span></div>"
            f"<div><h3><a href=\"{e(cfg.href(deal_path(d)))}\">{e(d.p)}</a>"
            f"{pos_badge(d)}</h3>"
            f"<p>{e(deal_sentence(d))}</p>"
            f'<p class="meta">{e(STATUS_LABEL.get(status, status))}'
            f"{f' · £{d.fee:g}m' if d.fee else ''}"
            f"{f' · {e(d.src)}' if d.src else ''}"
            f"{f' · updated {e(d.date)}' if d.date else ''}"
            f"{source_anchor(d)}</p>"
            f"{f'<p class=\"note\">{e(d.note)}</p>' if d.note else ''}"
            "</div></article>"
        )
    return "\n".join(rows)


def render_club_grid(clubs: dict, deals: list[Deal], cfg: SiteConfig) -> str:
    cards = []
    for club in sorted(clubs):
        incoming = [d for d in deals if d.to == club]
        spend = sum(d.fee or 0 for d in incoming if str(getattr(d.status, "value", d.status)) == "done")
        cards.append(
            f'<article class="clubcard"><h3>'
            f'<a href="{e(cfg.href(club_path(club)))}">{e(club)}</a></h3>'
            f"<p>{len(incoming)} tracked deals, £{spend:g}m committed this window.</p>"
            "</article>"
        )
    return "\n".join(cards)


def render_funnel(deals: list[Deal]) -> str:
    counts = {s: 0 for s in STATUS_ORDER}
    for d in deals:
        key = str(getattr(d.status, "value", d.status))
        counts[key] = counts.get(key, 0) + 1
    chips = [
        f'<div class="stagechip"><div class="n">{counts[s]}</div>'
        f"<div>{e(STATUS_LABEL[s])}</div></div>"
        for s in STATUS_ORDER
    ]
    return "\n".join(chips)


#: The pulse feed's default ordering, mirrored exactly in index.html.
#:
#: Collapsed first because a dead deal is the most surprising thing on the
#: page, then the stages closest to resolution, then the noise. Completed
#: deals sit near the bottom deliberately: they are settled, and a pulse is
#: about what is still moving.
FEED_RANK: dict[str, int] = {
    "collapsed": 0, "medical": 1, "confirmed": 2, "agreed": 3,
    "talks": 4, "done": 5, "rumor": 6,
}

_MONTHS = {m: i for i, m in enumerate(
    ["jan", "feb", "mar", "apr", "may", "jun",
     "jul", "aug", "sep", "oct", "nov", "dec"], start=1)}


def display_date_key(label: str) -> tuple[int, int]:
    """Sort key for the site's display dates, e.g. "Jul 8".

    Returns (0, 0) for anything unparseable, which sorts such rows last under
    a descending sort. A deal with no date is not recent news.
    """
    parts = (label or "").replace(",", " ").split()
    if len(parts) < 2:
        return (0, 0)
    month = _MONTHS.get(parts[0][:3].lower())
    if month is None:
        return (0, 0)
    try:
        return (month, int(parts[1]))
    except ValueError:
        return (month, 0)


def feed_order(deals: Iterable[Deal], mode: str = "active") -> list[Deal]:
    """Order the pulse feed. Must match the `FEED_SORTS` table in index.html.

    The pre-rendered feed used to sort by credibility then player name, while
    the browser sorted by stage then fee. The list therefore reordered itself
    the moment JavaScript ran, and readers without it got twelve completed
    deals in reverse alphabetical order, which is not a pulse.
    """
    rows = list(deals)
    if mode == "recent":
        return sorted(rows, key=lambda d: (display_date_key(d.date), d.fee or 0),
                      reverse=True)
    if mode == "fee":
        return sorted(rows, key=lambda d: (-(d.fee or 0), d.p))
    if mode == "cred":
        return sorted(rows, key=lambda d: (-d.cred, d.p))
    return sorted(
        rows,
        key=lambda d: (FEED_RANK.get(
            d.status.value if hasattr(d.status, "value") else str(d.status), 9),
            -(d.fee or 0), d.p),
    )


def render_feed_items(deals: list[Deal], mode: str = "active",
                      limit: int = 12) -> str:
    items = []
    for d in feed_order(deals, mode)[:limit]:
        items.append(
            f'<div class="item"><div class="when">{e(d.date or "")}</div>'
            f'<div class="what"><b>{e(d.p)}</b>{pos_badge(d)} '
            f'<span class="meta">{e(deal_sentence(d))}'
            f'{source_anchor(d)}</span></div></div>'
        )
    return "\n".join(items)


# ---------------------------------------------------------- structured data


def jsonld_website(cfg: SiteConfig, raw: dict) -> dict:
    return {
        "@context": "https://schema.org",
        "@type": "WebSite",
        "name": cfg.title,
        "url": cfg.url("/"),
        "description": cfg.description,
        "inLanguage": "en-GB",
        "author": {"@type": "Person", "name": cfg.author},
    }


def jsonld_dataset(cfg: SiteConfig, raw: dict, deals: list[Deal], updated: str) -> dict:
    """The site is, structurally, a dataset with a published methodology.
    Saying so is the most honest description available and it is the schema
    type most likely to be understood by something other than a search
    engine."""
    window = (raw.get("config") or {}).get("windowName", "")
    return {
        "@context": "https://schema.org",
        "@type": "Dataset",
        "name": f"{cfg.title}: {window} transfer credibility index".strip(),
        "description": (
            f"{len(deals)} tracked Premier League transfers, each scored 0 to 100 "
            "for credibility from source tier and corroboration, with fee and "
            "status history."
        ),
        "url": cfg.url("/"),
        "creator": {"@type": "Person", "name": cfg.author},
        "dateModified": updated,
        "isAccessibleForFree": True,
        "license": "https://creativecommons.org/licenses/by/4.0/",
        "variableMeasured": [
            {"@type": "PropertyValue", "name": "credibility", "minValue": 0, "maxValue": 100},
            {"@type": "PropertyValue", "name": "status"},
            {"@type": "PropertyValue", "name": "fee", "unitText": "GBP millions"},
        ],
    }


def jsonld_itemlist(cfg: SiteConfig, deals: list[Deal]) -> dict:
    return {
        "@context": "https://schema.org",
        "@type": "ItemList",
        "itemListElement": [
            {
                "@type": "ListItem",
                "position": i + 1,
                "url": cfg.url(deal_path(d)),
                "name": f"{d.p}: {d.from_club} to {d.to}",
            }
            for i, d in enumerate(deals)
        ],
    }


def jsonld_claimreview(cfg: SiteConfig, deal: Deal, updated: str) -> dict:
    """A credibility score on a reported transfer is, precisely, a review of a
    claim. The markup is valid regardless; Google's fact-check rich results
    additionally require acceptance into their programme, so treat any rich
    result as upside rather than the reason for doing this."""
    return {
        "@context": "https://schema.org",
        "@type": "ClaimReview",
        "url": cfg.url(deal_path(deal)),
        "datePublished": updated,
        "claimReviewed": f"{deal.p} is joining {deal.to} from {deal.from_club}.",
        "author": {"@type": "Organization", "name": cfg.title, "url": cfg.url("/")},
        "itemReviewed": {
            "@type": "Claim",
            "appearance": [{"@type": "CreativeWork", "url": ev.url} for ev in deal.evidence[:5]],
            "firstAppearance": {
                "@type": "CreativeWork",
                "url": deal.evidence[0].url if deal.evidence else cfg.url("/"),
            },
        },
        "reviewRating": {
            "@type": "Rating",
            "ratingValue": deal.cred,
            "bestRating": 100,
            "worstRating": 0,
            "alternateName": STATUS_LABEL.get(
                str(getattr(deal.status, "value", deal.status)), ""
            ),
        },
    }


def jsonld_breadcrumb(cfg: SiteConfig, trail: list[tuple[str, str]]) -> dict:
    return {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "name": name, "item": cfg.url(path)}
            for i, (name, path) in enumerate(trail)
        ],
    }


def script_ld(*blocks: dict) -> str:
    return "\n".join(
        '<script type="application/ld+json">'
        + json.dumps(b, ensure_ascii=False, separators=(",", ":"))
        + "</script>"
        for b in blocks
    )


# ---------------------------------------------------------------- head tags


def head_tags(
    cfg: SiteConfig,
    *,
    title: str,
    description: str,
    path: str,
    og_image: str,
    updated_iso: str,
    extra: str = "",
) -> str:
    canonical = cfg.url(path)
    tags = [
        GEN_START,
        f'<meta name="description" content="{e(description)}">',
        f'<link rel="canonical" href="{e(canonical)}">',
        '<meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1">',
        '<meta property="og:type" content="website">',
        f'<meta property="og:site_name" content="{e(cfg.title)}">',
        f'<meta property="og:title" content="{e(title)}">',
        f'<meta property="og:description" content="{e(description)}">',
        f'<meta property="og:url" content="{e(canonical)}">',
        f'<meta property="og:locale" content="{e(cfg.locale)}">',
        f'<meta property="og:image" content="{e(cfg.url(og_image))}">',
        '<meta property="og:image:width" content="1200">',
        '<meta property="og:image:height" content="630">',
        f'<meta property="og:image:alt" content="{e(title)}">',
        '<meta name="twitter:card" content="summary_large_image">',
        f'<meta name="twitter:title" content="{e(title)}">',
        f'<meta name="twitter:description" content="{e(description)}">',
        f'<meta name="twitter:image" content="{e(cfg.url(og_image))}">',
    ]
    if cfg.twitter:
        tags.append(f'<meta name="twitter:site" content="{e(cfg.twitter)}">')
    tags += [
        f'<meta name="author" content="{e(cfg.author)}">',
        f'<meta property="article:modified_time" content="{e(updated_iso)}">',
        f'<link rel="alternate" type="application/rss+xml" title="{e(cfg.title)} updates" '
        f'href="{e(cfg.href("feed.xml"))}">',
        f'<link rel="icon" href="{e(cfg.href("favicon.svg"))}" type="image/svg+xml">',
        '<meta name="theme-color" content="#0b0e14">',
    ]
    if extra:
        tags.append(extra)
    tags.append(GEN_END)
    return "\n".join(tags) + "\n"


# --------------------------------------------------------- standalone pages

PAGE_CSS = """
:root{--bg:#0b0e14;--panel:#131824;--border:#232c42;--text:#e8ecf4;
--muted:#8a94ab;--accent:#4f9cff;--green:#3ddc84;--amber:#ffb454;--red:#ff5d5d}
*{box-sizing:border-box;margin:0;padding:0}
body{background:var(--bg);color:var(--text);line-height:1.6;
font-family:'Segoe UI',system-ui,-apple-system,sans-serif}
.wrap{max-width:760px;margin:0 auto;padding:0 20px 72px}
a{color:var(--accent)}
header{border-bottom:1px solid var(--border);margin-bottom:28px;padding:22px 0}
h1{font-size:30px;letter-spacing:-.5px;margin:18px 0 6px}
h2{font-size:19px;margin:32px 0 10px}
.crumb{font-size:13px;color:var(--muted)}
.lede{color:var(--muted);margin-bottom:18px}
.score{display:flex;align-items:center;gap:18px;background:var(--panel);
border:1px solid var(--border);border-radius:12px;padding:18px;margin:18px 0}
.score .n{font-size:44px;font-weight:800;line-height:1}
.high{color:var(--green)}.mid{color:var(--accent)}.low{color:var(--amber)}.vlow{color:var(--red)}
table{width:100%;border-collapse:collapse;margin:14px 0;font-size:14.5px}
th,td{text-align:left;padding:9px 10px;border-bottom:1px solid var(--border)}
th{color:var(--muted);font-weight:600;font-size:12.5px;text-transform:uppercase;letter-spacing:.5px}
ul{margin:10px 0 10px 20px}
li{margin-bottom:6px}
.panel{background:var(--panel);border:1px solid var(--border);border-radius:12px;padding:18px;margin:16px 0}
footer{border-top:1px solid var(--border);margin-top:40px;padding-top:18px;
font-size:13px;color:var(--muted)}
""".strip()


def standalone_page(
    cfg: SiteConfig,
    *,
    title: str,
    description: str,
    path: str,
    og_image: str,
    updated_iso: str,
    breadcrumb: str,
    body: str,
    ld: str,
) -> str:
    return f"""<!DOCTYPE html>
<html lang="en-GB">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{e(title)}</title>
<style>{PAGE_CSS}</style>
{head_tags(cfg, title=title, description=description, path=path,
           og_image=og_image, updated_iso=updated_iso)}
{ld}
</head>
<body>
<div class="wrap">
<header>
  <p class="crumb">{breadcrumb}</p>
</header>
<main>
{body}
</main>
<footer>
  <p>{e(cfg.title)} · credibility, not clickbait · &copy; {date.today().year} {e(cfg.author)}</p>
  <p>Scores are computed from published reporting. They are an assessment of how
  well supported a claim is, not a prediction and not a betting signal.</p>
</footer>
</div>
</body>
</html>
"""


def render_deal_page(cfg: SiteConfig, deal: Deal, updated_iso: str, updated: str) -> str:
    status = str(getattr(deal.status, "value", deal.status))
    title = f"{deal.p} to {deal.to}: how credible is it? | {cfg.title}"
    description = (
        f"{deal.p} from {deal.from_club} to {deal.to} scores {deal.cred} out of 100 "
        f"for credibility. Status: {STATUS_LABEL.get(status, status)}. "
        "Sources and reasoning shown."
    )
    evidence = "".join(
        f'<li><a href="{e(ev.url)}" rel="nofollow noopener">{e(ev.source or ev.url)}</a>'
        f'{f" · tier {ev.tier}" if ev.tier else ""}'
        f'{f" · {e(ev.date)}" if ev.date else ""}</li>'
        for ev in deal.evidence
        if not str(ev.url).startswith("urn:")
    )
    body = f"""
<h1>{e(deal.p)}: {e(deal.from_club)} to {e(deal.to)}</h1>
<p class="lede">{e(deal_sentence(deal))}</p>
<div class="score">
  <div class="n {cred_class(deal.cred)}">{deal.cred}</div>
  <div><strong>Credibility, out of 100</strong><br>
  <span class="lede">{e(STATUS_LABEL.get(status, status))}
  {f"· reported fee £{deal.fee:g}m" if deal.fee else ""}</span></div>
</div>
{f'<div class="panel"><p>{e(deal.note)}</p></div>' if deal.note else ''}
<h2>Deal facts</h2>
<table>
<tr><th>Player</th><td>{e(deal.p)}</td></tr>
<tr><th>Position</th><td>{e(deal.pos or "Not stated")}</td></tr>
<tr><th>Age</th><td>{e(deal.age or "Not stated")}</td></tr>
<tr><th>From</th><td>{e(deal.from_club)}</td></tr>
<tr><th>To</th><td>{e(deal.to)}</td></tr>
<tr><th>Reported fee</th><td>{f"£{deal.fee:g}m" if deal.fee else "Undisclosed"}</td></tr>
<tr><th>Status</th><td>{e(STATUS_LABEL.get(status, status))}</td></tr>
<tr><th>Credibility</th><td>{deal.cred} / 100</td></tr>
<tr><th>Last updated</th><td>{e(deal.date or updated)}</td></tr>
</table>
<h2>Where the score comes from</h2>
<p>Credibility is computed, not written. The score rises with the tier of the
outlets reporting it and with independent corroboration, and decays when a deal
goes quiet. Only tier 1 and tier 2 sources can advance a deal's status.</p>
{f"<h2>Sources</h2><ul>{evidence}</ul>" if evidence else ""}
<p><a href="{e(cfg.href("/"))}">All tracked {e(deal.to)} deals and the full window index</a></p>
"""
    ld = script_ld(
        jsonld_claimreview(cfg, deal, updated_iso),
        jsonld_breadcrumb(
            cfg,
            [("Home", "/"), (deal.to, club_path(deal.to)), (deal.p, deal_path(deal))],
        ),
    )
    crumb = (
        f'<a href="{e(cfg.href("/"))}">TransferIntel</a> / '
        f'<a href="{e(cfg.href(club_path(deal.to)))}">{e(deal.to)}</a> / {e(deal.p)}'
    )
    return standalone_page(
        cfg, title=title, description=description, path=deal_path(deal),
        og_image=f"og/deal-{deal_slug(deal)}.png", updated_iso=updated_iso,
        breadcrumb=crumb, body=body, ld=ld,
    )


def render_club_page(
    cfg: SiteConfig, club: str, club_data: dict, deals: list[Deal],
    updated_iso: str, updated: str,
) -> str:
    incoming = [d for d in deals if d.to == club]
    outgoing = [d for d in deals if d.from_club == club]
    done = [d for d in incoming if str(getattr(d.status, "value", d.status)) == "done"]
    spend = sum(d.fee or 0 for d in done)

    title = f"{club} transfer news, spend and rumour credibility | {cfg.title}"
    description = (
        f"{club}: {len(incoming)} tracked incoming deals, £{spend:g}m committed. "
        "Every rumour scored 0 to 100 for credibility with sources shown."
    )

    def table(rows: list[Deal], other: str) -> str:
        if not rows:
            return "<p class=\"lede\">Nothing tracked yet this window.</p>"
        cells = "".join(
            f"<tr><td><a href=\"{e(cfg.href(deal_path(d)))}\">{e(d.p)}</a></td>"
            f"<td>{e(d.from_club if other == 'from' else d.to)}</td>"
            f"<td>{f'£{d.fee:g}m' if d.fee else 'Free'}</td>"
            f"<td>{e(STATUS_LABEL.get(str(getattr(d.status,'value',d.status)), ''))}</td>"
            f"<td>{d.cred}</td></tr>"
            for d in sorted(rows, key=lambda x: -x.cred)
        )
        head = "From" if other == "from" else "To"
        return (
            f"<table><thead><tr><th>Player</th><th>{head}</th><th>Fee</th>"
            f"<th>Status</th><th>Cred</th></tr></thead><tbody>{cells}</tbody></table>"
        )

    needs = club_data.get("needs") or []
    needs_html = (
        "<ul>" + "".join(f"<li>{e(n)}</li>" for n in needs) + "</ul>" if needs else ""
    )

    body = f"""
<h1>{e(club)} transfer window</h1>
<p class="lede">{e(description)}</p>
<div class="panel">
<table>
<tr><th>Tracked incoming</th><td>{len(incoming)}</td></tr>
<tr><th>Completed</th><td>{len(done)}</td></tr>
<tr><th>Committed spend</th><td>£{spend:g}m</td></tr>
<tr><th>Tracked outgoing</th><td>{len(outgoing)}</td></tr>
</table>
</div>
{f"<h2>Squad needs</h2>{needs_html}" if needs_html else ""}
<h2>Incoming</h2>
{table(incoming, "from")}
<h2>Outgoing</h2>
{table(outgoing, "to")}
<p><a href="{e(cfg.href("/"))}">Back to the full window index</a></p>
"""
    ld = script_ld(
        jsonld_breadcrumb(cfg, [("Home", "/"), (club, club_path(club))]),
        {
            "@context": "https://schema.org",
            "@type": "SportsTeam",
            "name": club,
            "sport": "Association football",
            "url": cfg.url(club_path(club)),
        },
    )
    crumb = f'<a href="{e(cfg.href("/"))}">TransferIntel</a> / {e(club)}'
    return standalone_page(
        cfg, title=title, description=description, path=club_path(club),
        og_image=f"og/club-{slugify(club)}.png", updated_iso=updated_iso,
        breadcrumb=crumb, body=body, ld=ld,
    )


# ---------------------------------------------------------------- plumbing


def render_sitemap(cfg: SiteConfig, entries: list[tuple[str, str, str]]) -> str:
    """entries: (path, lastmod ISO date, changefreq)."""
    urls = "".join(
        f"<url><loc>{e(cfg.url(path))}</loc><lastmod>{e(lastmod)}</lastmod>"
        f"<changefreq>{freq}</changefreq></url>"
        for path, lastmod, freq in entries
    )
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
        f"{urls}</urlset>\n"
    )


def render_robots(cfg: SiteConfig) -> str:
    """Permissive, with the sitemap declared.

    The AI crawlers are listed explicitly and allowed. That is a judgment
    call, not a default: for a site whose entire purpose is to be cited as a
    credibility source, being quotable by an assistant is distribution, not
    theft. Flip any of these to Disallow if you decide otherwise.
    """
    sitemap = cfg.url("sitemap.xml")
    return f"""# {cfg.title}
User-agent: *
Allow: /

# Assistants and answer engines. Allowed deliberately: this site exists to be
# cited. Change to Disallow if that stops being true.
User-agent: GPTBot
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: Google-Extended
Allow: /

# Build output and raw data have no reason to be indexed as pages.
User-agent: *
Disallow: /build/

Sitemap: {sitemap}
"""


def render_feed(cfg: SiteConfig, deals: list[Deal], updated_iso: str) -> str:
    """RSS of the deals that moved. A window site with no feed gives regular
    readers no way to come back without remembering to."""
    now = datetime.now(timezone.utc).strftime("%a, %d %b %Y %H:%M:%S +0000")
    items = []
    for d in sorted(deals, key=lambda x: -x.cred)[:30]:
        link = cfg.url(deal_path(d))
        items.append(
            "<item>"
            f"<title>{e(f'{d.p} to {d.to}: credibility {d.cred}/100')}</title>"
            f"<link>{e(link)}</link>"
            f"<guid isPermaLink=\"true\">{e(link)}</guid>"
            f"<description>{e(deal_sentence(d))}</description>"
            f"<pubDate>{now}</pubDate>"
            "</item>"
        )
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<rss version="2.0"><channel>'
        f"<title>{e(cfg.title)}</title>"
        f"<link>{e(cfg.url('/'))}</link>"
        f"<description>{e(cfg.description)}</description>"
        f"<language>en-gb</language><lastBuildDate>{now}</lastBuildDate>"
        f"{''.join(items)}"
        "</channel></rss>\n"
    )


def render_llms_txt(cfg: SiteConfig, deals: list[Deal], raw: dict, updated: str) -> str:
    """An emerging convention: a plain-text map of the site for assistants.
    Cheap to generate, and it states the methodology in the one place a model
    is most likely to read it."""
    window = (raw.get("config") or {}).get("windowName", "")
    lines = [
        f"# {cfg.title}",
        "",
        f"> {cfg.description}",
        "",
        f"Window: {window}. Last updated: {updated}.",
        "",
        "## Method",
        "",
        "Credibility scores are computed in code, not written by a model. A score "
        "rises with the tier of the outlets reporting a claim and with independent "
        "corroboration, and decays when a deal goes quiet. Only tier 1 and tier 2 "
        "outlets can advance a deal's status. A completed transfer requires a tier 1 "
        "source. Scores are an assessment of how well supported a claim is. They are "
        "not predictions and not betting advice.",
        "",
        "## Pages",
        "",
        f"- [Window index]({cfg.url('/')}): every tracked deal, funnel and club summary",
    ]
    for d in sorted(deals, key=lambda x: -x.cred):
        lines.append(
            f"- [{d.p}, {d.from_club} to {d.to}]({cfg.url(deal_path(d))}): "
            f"credibility {d.cred}/100"
        )
    return "\n".join(lines) + "\n"


def render_favicon() -> str:
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">'
        '<rect width="64" height="64" rx="14" fill="#0b0e14"/>'
        '<path d="M14 40 L26 22 L38 34 L50 16" fill="none" stroke="#4f9cff" '
        'stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/>'
        '<circle cx="50" cy="16" r="6" fill="#3ddc84"/></svg>\n'
    )


def render_404(cfg: SiteConfig) -> str:
    body = (
        "<h1>That page has moved on</h1>"
        "<p class=\"lede\">Transfers collapse, and so do URLs. The window index has "
        "everything currently tracked.</p>"
        f'<p><a href="{e(cfg.href("/"))}">Back to TransferIntel</a></p>'
    )
    return standalone_page(
        cfg, title=f"Page not found | {cfg.title}",
        description="Page not found.", path="404.html",
        og_image="og/default.png",
        updated_iso=datetime.now(timezone.utc).date().isoformat(),
        breadcrumb=f'<a href="{e(cfg.href("/"))}">TransferIntel</a> / not found',
        body=body, ld="",
    )
